[package]
name = "tool_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
async-trait = "0.1.82"
once_cell = "1.19.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0.128"
tokio = "1.40.0"
